#!/bin/sh

die() {
	trap - EXIT
	printf "\nERROR: missing fields\n"
	exit 1
}

BOOT_UCODE="${BOOT_UCODE:-amd-ucode.img}"
BOOT_INITRAMFS="${BOOT_INITRAMFS:-initramfs-lts}"
BOOT_LINUZ="${BOOT_LINUZ:-vmlinuz-lts}"
BOOT_LABEL="${BOOT_LABEL:-Alpine Linux}"

params="root=$BOOT_ROOT rw $BOOT_PARAMS \
	initrd=\\$BOOT_UCODE \
	initrd=\\$BOOT_INITRAMFS"

echo "root:      ${BOOT_ROOT:-(BOOT_ROOT missing)}"
echo "params:    ${BOOT_PARAMS:-(BOOT_PARAMS missing)}"
echo "ucode:     ${BOOT_UCODE:-(BOOT_UCODE missing)}"
echo "initramfs: ${BOOT_INITRAMFS:-(BOOT_INITRAMFS missing)}"
echo "label:     ${BOOT_LABEL:-(BOOT_LABEL missing)}"
echo "disk:      ${BOOT_DISK:-(BOOT_DISK missing)}"
echo "partition: ${BOOT_PART:-(BOOT_PART missing)}"
echo "linuz:     ${BOOT_LINUZ:-(BOOT_LINUZ missing)}"

[ -z "$BOOT_ROOT" ] && die
[ -z "$BOOT_PARAMS" ] && die
[ -z "$BOOT_DISK" ] && die
[ -z "$BOOT_PART" ] && die

printf "\nDo you wish to proceed? [Y/n] "
read -r yesno

if [ "$yesno" != "${yesno#[Yy]}" ]; then
	efibootmgr \
		--create \
		--label "$BOOT_LABEL" \
		--disk "$BOOT_DISK" \
		--part "$BOOT_PART" \
		--loader="\\$BOOT_LINUZ" \
		--unicode "$params" \
		--verbose
else
	echo "EFI stubbing aborted!"
	exit 1
fi

