#!/bin/sh

set -e

pkgdir="$1"
target_arch="${2:-$(uname --machine)}" # TODO
pkgdir="$PWD/$pkgdir"
priv_key="$(find "./public/keys/$target_arch" -name '*.rsa' -printf "%f\n")"

mkdir --parent data
echo "PACKAGER_PRIVKEY=/tmp/$priv_key" > data/abuild.conf

mkdir --parent "cache/$target_arch"

cat << EOF > data/repositories
$(for repo in public/repositories/*/; do echo "/var/my-aports/$(basename "$repo")/"; done)
https://dl-cdn.alpinelinux.org/alpine/edge/main
https://dl-cdn.alpinelinux.org/alpine/edge/community
https://dl-cdn.alpinelinux.org/alpine/edge/testing
EOF

user_args=""

if [ "$target_arch" = "$(uname --machine)" ]; then
	# Builds on 'x86_64' fail without this, while on 'aarch64' builds fail if not run as root.
	user_args="--userns=keep-id --group-add=abuild"
fi

podman container run \
	--rm \
	--tty \
	--interactive \
	$user_args \
	--env="REPODEST=/var/my-aports" \
	--env="SRCDEST=/var/cache/distfiles" \
	--workdir="$pkgdir" \
	--volume="$pkgdir:$pkgdir" \
	--volume="$PWD/public/repositories:/var/my-aports" \
	--volume="$PWD/cache/$target_arch:/var/cache/distfiles" \
	--volume="$PWD/data/repositories:/etc/apk/repositories" \
	--volume="$PWD/public/keys/$target_arch/$priv_key:/tmp/$priv_key" \
	--volume="$PWD/public/keys/$target_arch/$priv_key.pub:/etc/apk/keys/$priv_key.pub" \
	--volume="$PWD/data/abuild.conf:/etc/abuild.conf" \
	"my-aports-$target_arch" abuild -fFrc
