#!/bin/sh

set -e

pkgdir="$1"
arch="${2:-x86_64}" # TODO
pkgdir="$PWD/$pkgdir"
priv_key="$(find ./public/keys -name '*.rsa' -printf "%f\n")"

mkdir --parent data
echo "PACKAGER_PRIVKEY=/tmp/$priv_key" > data/abuild.conf

cat << EOF > repositories
$(for repo in public/repositories/*/; do echo "/var/my-aports/$(basename "$repo")"; done)
https://dl-cdn.alpinelinux.org/alpine/edge/main
https://dl-cdn.alpinelinux.org/alpine/edge/community
https://dl-cdn.alpinelinux.org/alpine/edge/testing
EOF

podman container run \
	--rm \
	--tty \
	--interactive \
	--userns=keep-id \
	--group-add=abuild \
	--env="REPODEST=/var/my-aports" \
	--env="SRCDEST=/var/cache/distfiles" \
	--workdir="$pkgdir" \
	--volume="$pkgdir:$pkgdir" \
	--volume="$PWD/public/repositories:/var/my-aports" \
	--volume="$PWD/cache:/var/cache/distfiles" \
	--volume="$PWD/repositories:/etc/apk/repositories" \
	--volume="$PWD/public/keys/$priv_key:/tmp/$priv_key" \
	--volume="$PWD/public/keys/$priv_key.pub:/etc/apk/keys/$priv_key.pub" \
	--volume="$PWD/data/abuild.conf:/etc/abuild.conf" \
	aports abuild -r
