#!/bin/sh

pkgdir="$1"
pkgdir="${PWD}/${pkgdir}"

mkdir --parent cache

podman container run \
	--rm \
	--tty \
	--interactive \
	--workdir="$pkgdir" \
	--volume="${pkgdir}:${pkgdir}" \
	--volume="${PWD}/cache:/var/cache/distfiles" \
	"my-aports-$(uname --machine)" abuild -fF checksum
