#!/bin/sh

set -e

repo="${1:-main}"
arch="${2:-x86_64}" # TODO

indexables="$(
	find "public/repositories/$repo/$arch" \
		-type f \
		-printf "%f\n" \
		\( -name 'APKINDEX.tar.gz' -or -name '*.apk' \) \
	| sort
)"

cat << EOF > repositories
$(for repo in public/repositories/*/; do echo "/var/my-aports/$(basename "$repo")"; done)
https://dl-cdn.alpinelinux.org/alpine/edge/main
https://dl-cdn.alpinelinux.org/alpine/edge/community
https://dl-cdn.alpinelinux.org/alpine/edge/testing
EOF

# shellcheck disable=SC2086
podman container run \
	--rm \
	--tty \
	--interactive \
	--userns=keep-id \
	--group-add=abuild \
	--workdir="/var/my-aports/$repo/$arch" \
	--volume="$PWD/public/repositories:/var/my-aports" \
	aports apk index -o $indexables
