#!/bin/sh

set -e

for repo in public/repositories/*/; do
	target_repo="$(basename "$repo")"

	for arch in "$repo"*; do
		target_arch="$(basename "$arch")"

		mkdir --parent "public/repositories/$target_repo/$target_arch"
		indexables="$(find "public/repositories/$target_repo/$target_arch" -name '*.apk' -printf "%f\n")"

		printf "%s/%s: " "$target_repo" "$target_arch"

		podman container run \
			--rm \
			--tty \
			--interactive \
			--workdir="/var/my-aports/$target_repo/$target_arch" \
			--volume="$PWD/public/repositories:/var/my-aports" \
			"my-aports-$target_arch" apk index -o APKINDEX.tar.gz $indexables
	done
done
