#!/bin/sh

author="$(git config --global user.name)"
author="$author <$(git config --global user.email)>"
target_arch="${1:-$(uname --machine)}" # TODO

mkdir --parent "public/keys/$target_arch"
rm --force public/keys/"$target_arch"/*

podman container run \
	--rm \
	--env="PACKAGER='${author}'" \
	--workdir=/tmp \
	--volume="${PWD}/public/keys/$target_arch:/tmp/.abuild" \
	"my-aports-$target_arch" abuild-keygen -n
