#!/bin/sh

pkgdir="$1"
pkgdir="$PWD/$pkgdir"

podman container run \
	--rm \
	--tty \
	--interactive \
	--workdir="$pkgdir" \
	--volume="$pkgdir:$pkgdir" \
	"my-aports-$(uname --machine)" apkbuild-lint APKBUILD
