#!/bin/sh

pkgdir="$1"
pkgdir="$PWD/$pkgdir"

podman container run \
	--rm \
	--tty \
	--interactive \
	--userns=keep-id \
	--workdir="$pkgdir" \
	--volume="$pkgdir:$pkgdir" \
	aports apkbuild-lint APKBUILD
