#!/bin/sh

set -e

for repo in public/repositories/*/; do
	target_repo="$(basename "$repo")"

	for arch in "$repo"*/; do
		target_arch="$(basename "$arch")"
		priv_key_path="$(find "public/keys/$target_arch" -name '*.rsa' -print)"
		priv_key="$(basename "$priv_key_path")"

		mkdir --parent data
		echo "PACKAGER_PRIVKEY=/tmp/$priv_key" > data/abuild.conf

		printf "%s/%s: " "$target_repo" "$target_arch"

		podman container run \
			--rm \
			--tty \
			--interactive \
			--env="REPODEST=/var/my-aports" \
			--workdir="/var/my-aports/$target_repo/$target_arch" \
			--volume="$PWD/public/repositories:/var/my-aports" \
			--volume="$PWD/$priv_key_path:/tmp/$priv_key" \
			--volume="$PWD/$priv_key_path.pub:/tmp/$priv_key.pub" \
			--volume="$PWD/data/abuild.conf:/etc/abuild.conf" \
			"my-aports-$target_arch" abuild-sign APKINDEX.tar.gz
	done
done
