#!/bin/sh

set -e

repo="${1:-main}"
arch="${2:-x86_64}" # TODO
priv_key="$(find ./public/keys -name '*.rsa' -printf "%f\n")"

mkdir --parent data
echo "PACKAGER_PRIVKEY=/tmp/$priv_key" > data/abuild.conf

cat << EOF > repositories
$(for repo in public/repositories/*/; do echo "/var/my-aports/$(basename "$repo")"; done)
https://dl-cdn.alpinelinux.org/alpine/edge/main
https://dl-cdn.alpinelinux.org/alpine/edge/community
https://dl-cdn.alpinelinux.org/alpine/edge/testing
EOF

podman container run \
	--rm \
	--interactive \
	--tty \
	--userns=keep-id \
	--group-add=abuild \
	--env="REPODEST=/var/my-aports" \
	--workdir="/var/my-aports/$repo/$arch" \
	--volume="$PWD/public/repositories:/var/my-aports" \
	--volume="$PWD/public/keys/$priv_key:/tmp/$priv_key" \
	--volume="$PWD/public/keys/$priv_key.pub:/tmp/$priv_key.pub" \
	--volume="$PWD/data/abuild.conf:/etc/abuild.conf" \
	aports abuild-sign APKINDEX.tar.gz
